# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dea8b26af0ca316e08787d43aadd3486580cf3b5576a2d5ce17775e3be33a17d6080061fb5f12e15efa59901a1082c6fddbb726b383ff4657c004b86fea0f879

test:
  secret_key_base: 2266e7785830ad31b1cc2c951b5a7be5e6dc16cd3e250e9e7f8897b9b14e26a0a75a5cd94776d91e0b38c15144c9d69395ac0a5b13673d7a484462ee033560da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
